### ISSUE TITLE
Single-point range fails (for 1e308)

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/herbie-vscode#10]

**Comment by elmisback** [comment]
Got:
```
RangeError: Invalid array length
	at choose_between (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/elm/herbie-vscode/out/webview/plugins/demo.js:615:20)
	at loop (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/elm/herbie-vscode/out/webview/plugins/demo.js:644:24)
	at loop (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/elm/herbie-vscode/out/webview/plugins/demo.js:644:80)
	at pick_spaced_ordinals (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/elm/herbie-vscode/out/webview/plugins/demo.js:645:11)
	at Object.choose_ticks [as chooseTicks] (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/elm/herbie-vscode/out/webview/plugins/demo.js:651:27)
	at https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/elm/herbie-vscode/out/webview/plugins/demo.js:528:35
	at Array.map (<anonymous>)
	at Object.analyzeExpression (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/elm/herbie-vscode/out/webview/plugins/demo.js:526:40)
	at async Proxy.analyzeExpression (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/elm/herbie-vscode/out/webview/plugins/demo.js:1948:17)
	at async stepRule (https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/elm/herbie-vscode/out/webview/plugins/platform.js:139:23)
```
for a range with just the point 1e308 for expression 1/(1-E^(-x))

**Comment by elmisback** [comment]
This is now technically prohibited by the range input. Closing for now.
